### ISSUE TITLE
showMessage = true does not work

### ISSUE THREAD

**Issue by Talfereg** [blockchaaain/LetMeSleep#2]
**Describe the bug**
'showMessage = true' does not work. It never shows when another player sleeps. Perhaps this has to be on the clients PC as well and not just the server?

**To Reproduce**
1. Sleep in bed

**Expected behavior**
message displaying when a player is sleeping

**System (please complete the following information):**
 - Valheim version - 214.300
 - BepInEx version - 5.4.2102
 - LetMeSleep version - 1.02

Also running Valheim Plus Fix

**Comment by blockchaaain** [comment]
If the mod is working at all, and it's installed on the server, I would expect the message to work.
It doesn't say who is sleeping.
It will only say how many are trying to sleep (but does appear whenever someone new goes to bed).

@Talfereg I can take a look at your specific case in Valheim and/or Discord

Not completely related but...
In retrospect, I should really put a try-catch on the message code since that's the part that keeps breaking with each Valheim update. 🤔

**Comment by blockchaaain** [comment]
If you use the [ValheimPlus hotfix by Grantapher](https://valheim.thunderstore.io/package/Grantapher/ValheimPlus_Grantapher_Temporary/), the mod should work as expected.
